name: Pre-commit auto-update

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 0 1 * *'  # Run on the 1st day of every month at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install pre-commit
        run: pip install pre-commit
        
      - name: Run pre-commit auto-update
        run: pre-commit autoupdate
        
      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-auto-update
          title: 'chore(deps): Auto-update pre-commit hooks'
          commit-message: 'chore(deps): Auto-update pre-commit hooks'
          body: |
            ## Auto-update pre-commit hooks
            
            This PR updates the versions of tools in `.pre-commit-config.yaml` to their latest versions.
            
            ### Changes
            - Updates pre-commit hook versions to latest available
            - Automatically generated by GitHub Actions
            
            ### Notes  
            - This PR will be automatically updated when new versions are available
            - Review the changes and merge when ready
            
            ---
            🤖 This PR was automatically created/updated by the `pre-commit auto-update` workflow
          delete-branch: true
          add-paths: |
            .pre-commit-config.yaml
